server.port: 8001
spring.cloud.config.server.git.uri: https://github.com/runnerdave/spring-cloud-config-data

# This controls which Actuator web endpoints are exposed.
# Ordinarily, only /actuator/health and /actuator/info are exposed,
# But we need to allow external parties to POST to /bus-refresh:
management.endpoints.web.exposure.include: health,info,bus-refresh